language: python

python:
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev

install:
- pip install -r requirements.txt
- pip install coveralls

script:
- pycodestyle --max-line-length=99 -r *.py app/*.py
- pytest --cov ../conp-portal 

after_success:
- coveralls
