language: python

python:
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev

before_install:
  - wget -O- http://neuro.debian.net/lists/xenial.us-nh.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
  - sudo apt-get -q update
  - sudo apt-get -y install git-annex

install:
- pip install -r requirements.txt
- pip install coveralls

script:
- pycodestyle --max-line-length=99 -r *.py app/*.py
- pytest --cov ../conp-portal 

after_success:
- coveralls
